services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./default_state.json:/backend/init/default_state.json
    environment:
      - CONFIG_PATH=/backend/init/default_state.json
    ports:
      - "5000:5000"